[package]
name = "wpnexp"
version = "1.0.0"
authors = ["battleship789"]
edition = "2021"

[package.metadata.skyline]
titleid = "0100a6301214e000" # Fire Emblem Engage

[workspace]
resolver = "2"
members = [
    ".",
    "crate",
]

[workspace.dependencies]
engage-il2cpp = { git = "https://github.com/DivineDragonFanClub/engage-il2cpp", tag = "0.1.2", default-features = false }
unity-nx = { git = "https://github.com/DivineDragonFanClub/unity-nx", tag = "0.1.2" }
cobapi = { git = "https://github.com/DivineDragonFanClub/cobapi", tag = "0.1.3" }
crtdapi = { path = "../crtdapi" }
skyline = "0.6.0"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.150"

[dependencies]
wpnexp_lib = { path = "crate" }
unity-nx = {workspace = true }
skyline = { workspace = true }
cobapi = { workspace = true }

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
